#!/bin/sh
# Runs after the package is installed (or upgraded).
set -e
update-desktop-database >/dev/null 2>&1 || true
gtk-update-icon-cache -f -t /usr/share/icons/hicolor >/dev/null 2>&1 || true
exit 0
